### PR TITLE
Added autocomplete keyboard shortcut.

### PR DESCRIPTION
**Pull request by Raiondesu**
+ Updated docs.

### CODE REVIEW

**Comment by andriasmelianus** [comment]
Hi,
How to modify default control for autocomplete from `Ctrl`+`Space` to only using `Enter` key?
I have tried controls props with this value, but no luck,
```
:controls="{
  select: [13, 32],
  autocomplete: [13]
}"
```
Easy saying, I just want to select the **first matching suggestion** on the list with `Enter` key only.
Thanks

**Comment by Raiondesu** [comment]
Hello. Unfortunately, this is impossible without modifying the component.

**Comment by andriasmelianus** [comment]
Hi @Raiondesu, will it be available on the next release?
It will speed up the input process.
Thanks

**Comment by Raiondesu** [comment]
@andriasmelianus, this is a very specific functionality. It would require breaking changes to implement on our side properly, so it's only possible for v2.0.
You can, however, do one of the following to fix your specific problem:

### 1. Extend `vue-simple-suggest`

There's nothing wrong with extending a third-party component.
You can extend it and override the `onAutocomplete` method.

The syntax is pretty simple:

```js
// YourComponent.js
import VueSimpleSuggest from 'vue-simple-suggest'

// This is a simple helper function we used to determine,
// if certain keycodes were activated in the specific keyboard event
import { hasKeyCode } from 'vue-simple-suggest/lib/misc'

export default {
  extends: VueSimpleSuggest,
  methods: {
    onAutocomplete (e) {
      if (hasKeyCode(this.controlScheme.autocomplete, e)
        // This is the line you needed to be gone, so I simply commented it
        // && (e.ctrlKey || e.shiftKey)
        && (this.suggestions.length > 0 && this.suggestions[0])
        && (this.listShown)
      ) {
        e.preventDefault()
        this.hover(this.suggestions[0])
        this.setText(this.displayProperty(this.suggestions[0]))
      }
    }
  }
}
```

### 2. Just replace the method!

You don't necessarily need to extend the component to change it's functionality! It's simple JS objects after all:

```js
import VueSimpleSuggest from 'vue-simple-suggest'

// The same helper function. Again, you don't have to use it. Rewrite it, if you want to.
import { hasKeyCode } from 'vue-simple-suggest/lib/misc'

VueSimpleSuggest.methods.onAutocomplete = function onAutocomplete (e) {
  if (hasKeyCode(this.controlScheme.autocomplete, e)
    // This is the line you needed to be gone, so I simply commented it
    // && (e.ctrlKey || e.shiftKey)
    && (this.suggestions.length > 0 && this.suggestions[0])
    && (this.listShown)
  ) {
    e.preventDefault()
    this.hover(this.suggestions[0])
    this.setText(this.displayProperty(this.suggestions[0]))
  }
}
```

And voila! You have a VueSimpleSuggest with a custom functionality!

**Comment by andriasmelianus** [comment]
Hi, thanks for the detailed explanation. :handshake: 
It seems that i need to improve my literature about VueJS

**Pull request merged**
