### PR TITLE
 New Feature for custom style injection

### PR DESCRIPTION
**Pull request by rcostalenz**
## **Please check if the PR fulfills these requirements**
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Introduces a new feature to inject CSS classes into the component.

## **What is the current behavior?** (You can also link to an open issue here)
The dev has to use the current class names to change the style.

## **What is the new behavior (if this is a feature change)?**
Dev can use existing classes.

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No new changes are necessary to current users.

### CODE REVIEW

**Comment by Raiondesu** [comment]
I agree with @kaskar2008, the feature is great overall.
@rcostalenz, I think you forgot to add customizable classes for `misc-item-above` and `misc-item-below`, though. :)
I think we'll accept your PR once you fix this little detail. :)

**Comment by rcostalenz** [comment]
Fix it! I am glad you guys like it.

**Comment by kaskar2008** [comment]
@rcostalenz, @Raiondesu I think it can't be done that way because `slot` is not a real dom element and it's not rendering itself as an element, so class bindings on `slot` is not a workaround. Any ideas how we can pass classes through?

**Comment by kaskar2008** [comment]
And I think those misc items can also be not a single element tho.

**Comment by Raiondesu** [comment]
@kaskar2008 Hmm

**Comment by Raiondesu** [comment]
@kaskar2008 This got me thinking now

**Comment by rcostalenz** [comment]
Actually, since slot can be fully customizable with templates there is no reason to have those, I remove them

**Comment by kaskar2008** [comment]
@rcostalenz Ok then

**Pull request merged**
