### PR TITLE
A very nice fork with transitions by @Lofbergio!

### PR DESCRIPTION
**Pull request by Raiondesu**
## **Please check if the PR fulfills these requirements**
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (I think this may be omitted for pushing to dev branch)

## **What kind of change does this PR introduce?**

Feature: ability to define transitions for the suggestions list.

## **Does this PR introduce a breaking change?**

No, but it's still a minor update.

### CODE REVIEW

**Comment by Raiondesu** [comment]
@kaskar2008, I think I can merge this?

It's going to a dev branch anyway.

**Comment by kaskar2008** [comment]
@Raiondesu Yep

**Comment by Lofbergio** [comment]
Thanks 👍 
I wish i could change the hardcoded class name though.

**Comment by Raiondesu** [comment]
@Lofbergio, hm, now that's an idea.
Gonna try implementing it this week.

**Pull request merged**
